### PR TITLE
fix(README): error imported name

### LINKED ISSUE #53: error imported name from dmn-js-properties-panel in README.md
### Steps to Reproduce

1. I saw these codes in `src/index.js` file write `export { default as CamundaPropertiesProviderModule } from './provider/camunda';`

2. So these codes below 
```
import {
  DmnPropertiesPanelModule,
  DmnPropertiesProviderModule,
  CamundaPropertiesProvider
} from 'dmn-js-properties-panel';
```

### Expected Behavior

should be 
```
import {
  DmnPropertiesPanelModule,
  DmnPropertiesProviderModule,
  CamundaPropertiesProviderModule
} from 'dmn-js-properties-panel';
```

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by andyqier88**
Closes #53 error imported name from dmn-js-properties-panel in README.md

### CODE REVIEW

**Comment by nikku** [comment]
@andyqier88 Thank you for your contribution. 

We'd need you to sign our CLA in order to be able to merge this.

**Comment by andyqier88** [comment]
> @andyqier88 Thank you for your contribution.
> 
> We'd need you to sign our CLA in order to be able to merge this.

ok

**Comment by andyqier88** [comment]
> @andyqier88 Thank you for your contribution.
> 
> We'd need you to sign our CLA in order to be able to merge this.

have signed

**Comment by nikku** [comment]
Thanks :)

**Pull request merged**
