### PR TITLE
fix(properties-panel): make sure to always paste as plain text

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/265

### CODE REVIEW

**Comment by barmac** [comment]
> Do you plan to port this one to our other properties panels, too?

Already done :)

**Comment by barmac** [comment]
CI fails due to a thing already fixed in dmn-js :(

**Comment by nikku** [comment]
Could you cut a dmn-js patch release and integrate it? Annoying to have CI fail all the time.

**Comment by barmac** [comment]
Sure.

**Pull request merged**
